name: website CI

on:
    push:
        paths:
            - "website/**"
        branches: ["**"]
    pull_request:
        paths:
            - "website/**"
        branches: ["**"]

jobs:
    check:
        name: Lint and format check
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: website

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Run check
              run: npm run check